version: 1.0.{build}
#branches:
#  only:
#  - master
image: Visual Studio 2017
init:
- ps: dotnet --info
install:
- appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v4.0.0/nuget.exe

build:
  project: MiLib NetCore.sln
  verbosity: minimal
build_script:
- cmd: >-
    dotnet build ./src/MiLibNetCore.Core/MiLibNetCore.Core.csproj -c Release

    dotnet build ./test/MiLibNetCore.Core.Test/MiLibNetCore.Core.Test.csproj -c Release

    dotnet pack  -c Release /p:PackageVersion=1.0.1
test_script:
- cmd: dotnet test ./test/MiLibNetCore.Core.Test/MiLibNetCore.Core.Test.csproj -c Release
artifacts:
- path: ./src/MiLibNetCore.Core/bin/Release/*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: 8d6lKC5lQ05TYPOMaXWrK0lKJhcn0ZyfnF3bVAiXGVQ1nJF1CB5GzrAEwyiTrDdH
  on:
    branch: master
