version: 1.0.{build}

#branches:
#  only:
#    - master

image: Visual Studio 2017

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

configuration: Release
platform: Any CPU

init:
- ps: dotnet --version

install:
  - ps: wget "https://raw.githubusercontent.com/rducom/ALM/master/build/ComputeVersion.ps1" -outfile "ComputeVersion.ps1"
  - ps: . .\ComputeVersion.ps1
  - ps: $version = Compute "src/MiLibNetCore.Core/MiLibNetCore.Core.csproj" $env:APPVEYOR_BUILD_NUMBER $env:APPVEYOR_REPO_TAG $env:APPVEYOR_PULL_REQUEST_NUMBER
  - ps: Update-AppveyorBuild -Version $version.Semver

build:
  project: MiLib NetCore.sln
  verbosity: minimal

build_script:
- ps: dotnet build -c Debug -v minimal

test_script:
- cmd: dotnet test ./test/MiLibNetCore.Core.Test/MiLibNetCore.Core.Test.csproj 

after_test:
- ps: dotnet pack --include-symbols -p:SymbolPackageFormat=snupkg /p:$("VersionPrefix="+$version.Prefix+";VersionSuffix="+$version.Suffix) /p:Configuration=Release /p:PackageVersion=$env:APPVEYOR_BUILD_VERSION -o ..\..\artifacts

artifacts:
- path: .\artifacts\**\*.nupkg

deploy:
- provider: NuGet
  api_key:
    secure: 8d6lKC5lQ05TYPOMaXWrK0lKJhcn0ZyfnF3bVAiXGVQ1nJF1CB5GzrAEwyiTrDdH
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    branch: master
    appveyor_repo_tag: true
